# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: TVasilev.RainDriver
PackageVersion: 0.4.0
InstallerType: portable
Commands:
- raindriver
MinimumOSVersion: 10.0.14393.0
ReleaseDate: '2026-10-04'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/raincleaner/RainDriver/releases/download/v0.4.0/RainDriver-0.4.0-win10-11-x64.exe
  InstallerSha256: 7B99872D87A94E69D1AD085A22D9A83064B31B8FEC2C983C9154A6843720CEE6
- Architecture: x86
  InstallerUrl: https://github.com/raincleaner/RainDriver/releases/download/v0.4.0/RainDriver-0.4.0-win10-x86.exe
  InstallerSha256: 4F13B79D990FD6A9A966C3F1698B153FD987256A9263AF082BCBC40F28BDA07C
ManifestType: installer
ManifestVersion: 1.12.0
