# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: TVasilev.RainDriver
PackageVersion: 1.0.1
InstallerType: portable
Commands:
- raindriver
MinimumOSVersion: 10.0.14393.0
ReleaseDate: '2026-10-07'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/raincleaner/RainDriver/releases/download/v1.0.1/RainDriver-1.0.1-win10-11-x64.exe
  InstallerSha256: 0F011C7FA4D2187A86C1266B9945D17576B29352E262DA3578DC968371CA9EF1
- Architecture: x86
  InstallerUrl: https://github.com/raincleaner/RainDriver/releases/download/v1.0.1/RainDriver-1.0.1-win10-x86.exe
  InstallerSha256: B5F4A5949C7D98539A807C5172CB9CE6A4BA8F59363CA686BB4C26387C005AF3
ManifestType: installer
ManifestVersion: 1.12.0
